ontology:
  ontology_directory_path: ${PROJECT_ROOT}data/ontology/

LLM:
  model: "gpt-4o"
  streaming: false
  temperature: 0

extractor_examples:
  individual_directory_path:  ${PROJECT_ROOT}data/extractor_examples/concept/
  concept_file_path: "{{individual_directory_path}}concepts.json"

